databases:
  - name: job-tracker-db
    plan: free

services:
  - type: web
    name: job-tracker-api
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 main:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-tracker-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://job-tracker-ui.onrender.com
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
